# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(695, 561)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 40, 611, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_35 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_35.sizePolicy().hasHeightForWidth())
        self.checkBox_35.setSizePolicy(sizePolicy)
        self.checkBox_35.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_35.setText("")
        self.checkBox_35.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_35.setCheckable(True)
        self.checkBox_35.setChecked(False)
        self.checkBox_35.setTristate(False)
        self.checkBox_35.setObjectName("checkBox_35")
        self.gridLayout.addWidget(self.checkBox_35, 6, 4, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_22.sizePolicy().hasHeightForWidth())
        self.checkBox_22.setSizePolicy(sizePolicy)
        self.checkBox_22.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_22.setText("")
        self.checkBox_22.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_22.setCheckable(True)
        self.checkBox_22.setChecked(False)
        self.checkBox_22.setTristate(False)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout.addWidget(self.checkBox_22, 4, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_5.sizePolicy().hasHeightForWidth())
        self.checkBox_5.setSizePolicy(sizePolicy)
        self.checkBox_5.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_5.setText("")
        self.checkBox_5.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_5.setCheckable(True)
        self.checkBox_5.setChecked(False)
        self.checkBox_5.setTristate(False)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 0, 4, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_31.sizePolicy().hasHeightForWidth())
        self.checkBox_31.setSizePolicy(sizePolicy)
        self.checkBox_31.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_31.setText("")
        self.checkBox_31.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_31.setCheckable(True)
        self.checkBox_31.setChecked(False)
        self.checkBox_31.setTristate(False)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout.addWidget(self.checkBox_31, 6, 0, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_9.sizePolicy().hasHeightForWidth())
        self.checkBox_9.setSizePolicy(sizePolicy)
        self.checkBox_9.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_9.setText("")
        self.checkBox_9.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_9.setCheckable(True)
        self.checkBox_9.setChecked(False)
        self.checkBox_9.setTristate(False)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 1, 3, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_26.sizePolicy().hasHeightForWidth())
        self.checkBox_26.setSizePolicy(sizePolicy)
        self.checkBox_26.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_26.setText("")
        self.checkBox_26.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_26.setCheckable(True)
        self.checkBox_26.setChecked(False)
        self.checkBox_26.setTristate(False)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout.addWidget(self.checkBox_26, 5, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox.setText("")
        self.checkBox.setIconSize(QtCore.QSize(32, 32))
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_7.sizePolicy().hasHeightForWidth())
        self.checkBox_7.setSizePolicy(sizePolicy)
        self.checkBox_7.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_7.setText("")
        self.checkBox_7.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_7.setCheckable(True)
        self.checkBox_7.setChecked(False)
        self.checkBox_7.setTristate(False)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 1, 1, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_23.sizePolicy().hasHeightForWidth())
        self.checkBox_23.setSizePolicy(sizePolicy)
        self.checkBox_23.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_23.setText("")
        self.checkBox_23.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_23.setCheckable(True)
        self.checkBox_23.setChecked(False)
        self.checkBox_23.setTristate(False)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout.addWidget(self.checkBox_23, 4, 2, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_34.sizePolicy().hasHeightForWidth())
        self.checkBox_34.setSizePolicy(sizePolicy)
        self.checkBox_34.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_34.setText("")
        self.checkBox_34.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_34.setCheckable(True)
        self.checkBox_34.setChecked(False)
        self.checkBox_34.setTristate(False)
        self.checkBox_34.setObjectName("checkBox_34")
        self.gridLayout.addWidget(self.checkBox_34, 6, 3, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_17.sizePolicy().hasHeightForWidth())
        self.checkBox_17.setSizePolicy(sizePolicy)
        self.checkBox_17.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_17.setText("")
        self.checkBox_17.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_17.setCheckable(True)
        self.checkBox_17.setChecked(False)
        self.checkBox_17.setTristate(False)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout.addWidget(self.checkBox_17, 3, 1, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_15.sizePolicy().hasHeightForWidth())
        self.checkBox_15.setSizePolicy(sizePolicy)
        self.checkBox_15.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_15.setText("")
        self.checkBox_15.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_15.setCheckable(True)
        self.checkBox_15.setChecked(False)
        self.checkBox_15.setTristate(False)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout.addWidget(self.checkBox_15, 2, 4, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_24.sizePolicy().hasHeightForWidth())
        self.checkBox_24.setSizePolicy(sizePolicy)
        self.checkBox_24.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_24.setText("")
        self.checkBox_24.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_24.setCheckable(True)
        self.checkBox_24.setChecked(False)
        self.checkBox_24.setTristate(False)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout.addWidget(self.checkBox_24, 4, 3, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_33.sizePolicy().hasHeightForWidth())
        self.checkBox_33.setSizePolicy(sizePolicy)
        self.checkBox_33.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_33.setText("")
        self.checkBox_33.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_33.setCheckable(True)
        self.checkBox_33.setChecked(False)
        self.checkBox_33.setTristate(False)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout.addWidget(self.checkBox_33, 6, 2, 1, 1)
        self.currentNumberLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.currentNumberLabel.setText("")
        self.currentNumberLabel.setObjectName("currentNumberLabel")
        self.gridLayout.addWidget(self.currentNumberLabel, 7, 2, 1, 3)
        self.checkBox_16 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_16.sizePolicy().hasHeightForWidth())
        self.checkBox_16.setSizePolicy(sizePolicy)
        self.checkBox_16.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_16.setText("")
        self.checkBox_16.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_16.setCheckable(True)
        self.checkBox_16.setChecked(False)
        self.checkBox_16.setTristate(False)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout.addWidget(self.checkBox_16, 3, 0, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_27.sizePolicy().hasHeightForWidth())
        self.checkBox_27.setSizePolicy(sizePolicy)
        self.checkBox_27.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_27.setText("")
        self.checkBox_27.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_27.setCheckable(True)
        self.checkBox_27.setChecked(False)
        self.checkBox_27.setTristate(False)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout.addWidget(self.checkBox_27, 5, 1, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_29.sizePolicy().hasHeightForWidth())
        self.checkBox_29.setSizePolicy(sizePolicy)
        self.checkBox_29.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_29.setText("")
        self.checkBox_29.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_29.setCheckable(True)
        self.checkBox_29.setChecked(False)
        self.checkBox_29.setTristate(False)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout.addWidget(self.checkBox_29, 5, 3, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_11.sizePolicy().hasHeightForWidth())
        self.checkBox_11.setSizePolicy(sizePolicy)
        self.checkBox_11.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_11.setText("")
        self.checkBox_11.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_11.setCheckable(True)
        self.checkBox_11.setChecked(False)
        self.checkBox_11.setTristate(False)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout.addWidget(self.checkBox_11, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 2)
        self.checkBox_32 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_32.sizePolicy().hasHeightForWidth())
        self.checkBox_32.setSizePolicy(sizePolicy)
        self.checkBox_32.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_32.setText("")
        self.checkBox_32.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_32.setCheckable(True)
        self.checkBox_32.setChecked(False)
        self.checkBox_32.setTristate(False)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout.addWidget(self.checkBox_32, 6, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_4.setText("")
        self.checkBox_4.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_4.setCheckable(True)
        self.checkBox_4.setChecked(False)
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 0, 3, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_2.setText("")
        self.checkBox_2.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_10.sizePolicy().hasHeightForWidth())
        self.checkBox_10.setSizePolicy(sizePolicy)
        self.checkBox_10.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_10.setText("")
        self.checkBox_10.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_10.setCheckable(True)
        self.checkBox_10.setChecked(False)
        self.checkBox_10.setTristate(False)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 1, 4, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_8.sizePolicy().hasHeightForWidth())
        self.checkBox_8.setSizePolicy(sizePolicy)
        self.checkBox_8.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_8.setText("")
        self.checkBox_8.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_8.setCheckable(True)
        self.checkBox_8.setChecked(False)
        self.checkBox_8.setTristate(False)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 1, 2, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_20.sizePolicy().hasHeightForWidth())
        self.checkBox_20.setSizePolicy(sizePolicy)
        self.checkBox_20.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_20.setText("")
        self.checkBox_20.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_20.setCheckable(True)
        self.checkBox_20.setChecked(False)
        self.checkBox_20.setTristate(False)
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout.addWidget(self.checkBox_20, 3, 4, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_30.sizePolicy().hasHeightForWidth())
        self.checkBox_30.setSizePolicy(sizePolicy)
        self.checkBox_30.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_30.setText("")
        self.checkBox_30.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_30.setCheckable(True)
        self.checkBox_30.setChecked(False)
        self.checkBox_30.setTristate(False)
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout.addWidget(self.checkBox_30, 5, 4, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_19.sizePolicy().hasHeightForWidth())
        self.checkBox_19.setSizePolicy(sizePolicy)
        self.checkBox_19.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_19.setText("")
        self.checkBox_19.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_19.setCheckable(True)
        self.checkBox_19.setChecked(False)
        self.checkBox_19.setTristate(False)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout.addWidget(self.checkBox_19, 3, 3, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_12.sizePolicy().hasHeightForWidth())
        self.checkBox_12.setSizePolicy(sizePolicy)
        self.checkBox_12.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_12.setText("")
        self.checkBox_12.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_12.setCheckable(True)
        self.checkBox_12.setChecked(False)
        self.checkBox_12.setTristate(False)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 2, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_6.sizePolicy().hasHeightForWidth())
        self.checkBox_6.setSizePolicy(sizePolicy)
        self.checkBox_6.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_6.setText("")
        self.checkBox_6.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_6.setCheckable(True)
        self.checkBox_6.setChecked(False)
        self.checkBox_6.setTristate(False)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 1, 0, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_28.sizePolicy().hasHeightForWidth())
        self.checkBox_28.setSizePolicy(sizePolicy)
        self.checkBox_28.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_28.setText("")
        self.checkBox_28.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_28.setCheckable(True)
        self.checkBox_28.setChecked(False)
        self.checkBox_28.setTristate(False)
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout.addWidget(self.checkBox_28, 5, 2, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_14.sizePolicy().hasHeightForWidth())
        self.checkBox_14.setSizePolicy(sizePolicy)
        self.checkBox_14.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_14.setText("")
        self.checkBox_14.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_14.setCheckable(True)
        self.checkBox_14.setChecked(False)
        self.checkBox_14.setTristate(False)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout.addWidget(self.checkBox_14, 2, 3, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_18.sizePolicy().hasHeightForWidth())
        self.checkBox_18.setSizePolicy(sizePolicy)
        self.checkBox_18.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_18.setText("")
        self.checkBox_18.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_18.setCheckable(True)
        self.checkBox_18.setChecked(False)
        self.checkBox_18.setTristate(False)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout.addWidget(self.checkBox_18, 3, 2, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_21.sizePolicy().hasHeightForWidth())
        self.checkBox_21.setSizePolicy(sizePolicy)
        self.checkBox_21.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_21.setText("")
        self.checkBox_21.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_21.setCheckable(True)
        self.checkBox_21.setChecked(False)
        self.checkBox_21.setTristate(False)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout.addWidget(self.checkBox_21, 4, 0, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_25.sizePolicy().hasHeightForWidth())
        self.checkBox_25.setSizePolicy(sizePolicy)
        self.checkBox_25.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_25.setText("")
        self.checkBox_25.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_25.setCheckable(True)
        self.checkBox_25.setChecked(False)
        self.checkBox_25.setTristate(False)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout.addWidget(self.checkBox_25, 4, 4, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_13.sizePolicy().hasHeightForWidth())
        self.checkBox_13.setSizePolicy(sizePolicy)
        self.checkBox_13.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_13.setText("")
        self.checkBox_13.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_13.setCheckable(True)
        self.checkBox_13.setChecked(False)
        self.checkBox_13.setTristate(False)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout.addWidget(self.checkBox_13, 2, 2, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setStyleSheet("QCheckBox::indicator { width: 50; height: 50px;}\n"
"QCheckBox:indicator:checked {\n"
"        background-color: black\n"
";\n"
"    }")
        self.checkBox_3.setText("")
        self.checkBox_3.setIconSize(QtCore.QSize(32, 32))
        self.checkBox_3.setCheckable(True)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 0, 2, 1, 1)
        self.number_label_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.number_label_text.setObjectName("number_label_text")
        self.gridLayout.addWidget(self.number_label_text, 8, 2, 1, 3)
        self.save_as_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save_as_button.setObjectName("save_as_button")
        self.gridLayout.addWidget(self.save_as_button, 8, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.predict_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.predict_label.setObjectName("predict_label")
        self.horizontalLayout_2.addWidget(self.predict_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.predictButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.predictButton.setObjectName("predictButton")
        self.verticalLayout.addWidget(self.predictButton)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Label:"))
        self.save_as_button.setText(_translate("Dialog", "save as "))
        self.label_3.setText(_translate("Dialog", "TextLabel"))
        self.predict_label.setText(_translate("Dialog", "result"))
        self.predictButton.setText(_translate("Dialog", "predict"))
        self.pushButton.setText(_translate("Dialog", "clear"))
